[package]
name = "guest"
version = "0.1.0"
authors = ["David Antliff <david.antliff@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
heapless = "0.9.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
