[build]
target = "wasm32-unknown-unknown"

# Set the memory size and stack size for the constrained WebAssembly target
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=-zstack-size=8192", # default is 1048576
    #"-C", "target-feature=-bulk-memory,-reference-types,-multivalue,-sign-ext,-nontrapping-fptoint",
    #"-C", "link-arg=--import-memory", # use memory defined by the host
    #"-C", "link-arg=--initial-memory=65536",
    #"-C", "link-arg=--initial-memory=1048576",
]
