[build]
target = "wasm32-unknown-unknown"
#target = "wasm32v1-none"

# Set the memory size and stack size for the constrained WebAssembly target
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=-zstack-size=8192",
    "-C", "link-arg=--initial-memory=65536",
#    "-C", "target-feature=-bulk-memory,-reference-types,-multivalue,-sign-ext,-nontrapping-fptoint",
]

[target.wasm32v1-none]
rustflags = [
    "-C", "link-arg=-zstack-size=8192",
    "-C", "link-arg=--initial-memory=65536",
]
